package com.bballtending.android

import com.bballtending.android.domain.game.model.GameData
import com.bballtending.android.domain.game.model.GameType
import com.bballtending.android.domain.player.model.PlayerData
import com.bballtending.android.domain.player.model.Position
import java.time.LocalDate

object TestModule {
    /**
     * 2024-03-14 댈러스 vs 골든스테이트 경기 기록을 반환하는 함수
     */
    fun createTestData(): GameData {
        val nowDate = LocalDate.now()
        return GameData(
            gameId = 1,
            year = nowDate.year,
            month = nowDate.monthValue,
            day = nowDate.dayOfMonth,
            hour = 13,
            minute = 0,
            gameType = GameType.FULL_COURT,
            quarter = 4,
            playTime = 8,
            breakTime = 2,
            homeTeamName = "댈러스",
            awayTeamName = "골든스테이트",
            homeTeamTotalScore = 109,
            awayTeamTotalScore = 99,
            homeTeamScoreByQuarter = listOf(27, 21, 28, 33),
            awayTeamScoreByQuarter = listOf(27, 15, 28, 29),
            homeTeamPlayer = listOf(
                PlayerData(
                    playerId = 1,
                    name = "카이리 어빙",
                    number = "11",
                    position = Position.PG,
                    score = 23,
                    fieldGoalAttempt = 16,
                    fieldGoalSuccess = 8,
                    twoPointAttempt = 11,
                    twoPointSuccess = 7,
                    threePointAttempt = 5,
                    threePointSuccess = 1,
                    rebound = 8,
                    assist = 10,
                    steal = 1,
                    block = 1,
                    turnOver = 1,
                    foul = 3
                ),
                PlayerData(
                    playerId = 2,
                    name = "P.J. 워싱턴",
                    number = "25",
                    position = Position.PF,
                    score = 11,
                    fieldGoalAttempt = 11,
                    fieldGoalSuccess = 5,
                    twoPointAttempt = 5,
                    twoPointSuccess = 4,
                    threePointAttempt = 6,
                    threePointSuccess = 1,
                    rebound = 7,
                    assist = 1,
                    steal = 2,
                    block = 3,
                    turnOver = 1,
                    foul = 1
                ),
                PlayerData(
                    playerId = 3,
                    name = "루카 돈치치",
                    number = "77",
                    position = Position.SG,
                    score = 21,
                    fieldGoalAttempt = 18,
                    fieldGoalSuccess = 7,
                    twoPointAttempt = 12,
                    twoPointSuccess = 6,
                    threePointAttempt = 6,
                    threePointSuccess = 1,
                    rebound = 3,
                    assist = 9,
                    steal = 0,
                    block = 0,
                    turnOver = 6,
                    foul = 0
                ),
                PlayerData(
                    playerId = 4,
                    name = "다니엘 개포드",
                    number = "21",
                    position = Position.C,
                    score = 10,
                    fieldGoalAttempt = 5,
                    fieldGoalSuccess = 5,
                    twoPointAttempt = 5,
                    twoPointSuccess = 5,
                    threePointAttempt = 0,
                    threePointSuccess = 0,
                    rebound = 6,
                    assist = 1,
                    steal = 2,
                    block = 7,
                    turnOver = 2,
                    foul = 4
                ),
                PlayerData(
                    playerId = 5,
                    name = "데릭 존스 주니어",
                    number = "55",
                    position = Position.SF,
                    score = 7,
                    fieldGoalAttempt = 4,
                    fieldGoalSuccess = 3,
                    twoPointAttempt = 3,
                    twoPointSuccess = 3,
                    threePointAttempt = 1,
                    threePointSuccess = 0,
                    rebound = 3,
                    assist = 0,
                    steal = 0,
                    block = 0,
                    turnOver = 2,
                    foul = 0
                )
            ),
            awayTeamPlayer = listOf(
                PlayerData(
                    playerId = 6,
                    name = "조나단 쿠밍가",
                    number = "00",
                    position = Position.PF,
                    score = 27,
                    fieldGoalAttempt = 17,
                    fieldGoalSuccess = 8,
                    twoPointAttempt = 15,
                    twoPointSuccess = 6,
                    threePointAttempt = 2,
                    threePointSuccess = 2,
                    rebound = 4,
                    assist = 2,
                    steal = 1,
                    block = 0,
                    turnOver = 6,
                    foul = 2
                ),
                PlayerData(
                    playerId = 7,
                    name = "크리스 폴",
                    number = "3",
                    position = Position.PG,
                    score = 9,
                    fieldGoalAttempt = 12,
                    fieldGoalSuccess = 4,
                    twoPointAttempt = 8,
                    twoPointSuccess = 3,
                    threePointAttempt = 4,
                    threePointSuccess = 1,
                    rebound = 4,
                    assist = 4,
                    steal = 0,
                    block = 0,
                    turnOver = 0,
                    foul = 3
                ),
                PlayerData(
                    playerId = 8,
                    name = "앤드류 위긴스",
                    number = "22",
                    position = Position.SF,
                    score = 17,
                    fieldGoalAttempt = 12,
                    fieldGoalSuccess = 5,
                    twoPointAttempt = 8,
                    twoPointSuccess = 4,
                    threePointAttempt = 4,
                    threePointSuccess = 1,
                    rebound = 5,
                    assist = 1,
                    steal = 1,
                    block = 0,
                    turnOver = 2,
                    foul = 1
                ),
                PlayerData(
                    playerId = 9,
                    name = "클레이 톰슨",
                    number = "11",
                    position = Position.SG,
                    score = 8,
                    fieldGoalAttempt = 13,
                    fieldGoalSuccess = 3,
                    twoPointAttempt = 6,
                    twoPointSuccess = 1,
                    threePointAttempt = 7,
                    threePointSuccess = 2,
                    rebound = 4,
                    assist = 0,
                    steal = 1,
                    block = 1,
                    turnOver = 2,
                    foul = 0
                ),
                PlayerData(
                    playerId = 10,
                    name = "트레이스 잭슨-데이비스",
                    number = "32",
                    position = Position.C,
                    score = 10,
                    fieldGoalAttempt = 9,
                    fieldGoalSuccess = 5,
                    twoPointAttempt = 9,
                    twoPointSuccess = 5,
                    threePointAttempt = 0,
                    threePointSuccess = 0,
                    rebound = 9,
                    assist = 1,
                    steal = 0,
                    block = 1,
                    turnOver = 1,
                    foul = 1
                )
            )
        )
    }
}